// GENERATED by scripts/generate-public-assets.mjs — do not edit by hand.
// Run `pnpm generate:public-assets` after adding or removing a file in public/
// or a root metadata convention in src/app/.
// src/lib/public-assets.test.ts fails if this drifts.

/**
 * Root paths the proxy must pass straight through.
 *
 * Until 2026-08-06 the matcher excluded every path containing a dot, which kept
 * `/logo.svg` out of the proxy — and `/admin.php` with it, so junk URLs
 * bypassed the invalid-first-segment gate and answered 200 + index,follow with a
 * self-canonical. Now the matcher lets dotted paths in, and this is how the real
 * assets are told apart from the junk: `/logo.svg` looks exactly like a bogus
 * market prefix from the outside.
 */
export const PUBLIC_ASSET_PATHS: ReadonlySet<string> = new Set([
	"/android-chrome-192x192.png",
	"/android-chrome-512x512.png",
	"/favicon-16x16.png",
	"/favicon-32x32.png",
	"/favicon-dark-16x16.png",
	"/favicon-dark-32x32.png",
	"/github-mark.svg",
	"/llms.txt",
	"/logo-dark.svg",
	"/logo-deer.webp",
	"/logo.svg",
	"/screenshot.png",
	"/site.webmanifest",
]);

/** Next's own root metadata routes (robots.ts -> /robots.txt, and friends). */
export const METADATA_ROUTE_PATHS: ReadonlySet<string> = new Set([
	"/apple-icon.png",
	"/favicon.ico",
	"/icon.png",
	"/opengraph-image.png",
	"/robots.txt",
	"/sitemap.xml",
	"/twitter-image.png",
]);
