/**
 * The withdrawal submission contract.
 *
 * One legal process, one backend contract, two UX modes. A guest and a signed-in
 * customer submit the *same* body to the *same* endpoint and produce the same kind of
 * record; `source` only says which path filled the fields in. Registration must never
 * be a condition of exercising the right, so nothing here may depend on a session.
 *
 * Shared by the server action, the validator, the Payload client and the tests, so the
 * shape lives in exactly one place.
 */

export const WITHDRAWAL_CONTRACT_VERSION = 1;

/** V1 is SK-only. Other markets fall through to the route's not-launched behaviour. */
export const WITHDRAWAL_MARKET = "SK";
export const WITHDRAWAL_LOCALE = "sk";

export type WithdrawalSource = "guest" | "account";
export type WithdrawalScope = "wholeOrder" | "selectedItems";

/**
 * How the CMS matched the submission to a real order. Advisory only.
 *
 * None of these values may block a submission. A customer who mistypes an order
 * number, ordered under a different e-mail, or is withdrawing before delivery still
 * gave a legally effective notice; the mismatch is an internal review state, not a
 * rejection. The storefront never computes this — the server owns it.
 */
export type OrderMatchStatus = "pending" | "matched" | "notFound" | "emailMismatch" | "manualReview";

export interface WithdrawalItem {
	/** Saleor order line id, or `null` when the customer described the item by hand. */
	readonly orderLineId: string | null;
	readonly productName: string;
	/**
	 * Not currently available: the order query's variant selection does not request
	 * `sku`, and changing a Saleor GraphQL document needs sign-off (CLAUDE.md §10).
	 * Always `null` in V1 — `orderLineId` plus `productName` identify the item.
	 */
	readonly sku: string | null;
	readonly quantity: number;
}

export interface WithdrawalSubmission {
	readonly submissionId: string;
	readonly source: WithdrawalSource;
	readonly market: typeof WITHDRAWAL_MARKET;
	readonly locale: typeof WITHDRAWAL_LOCALE;
	readonly customer: {
		readonly name: string;
		readonly email: string;
		/** Optional. Never required — § 20a asks for an online contact, not a phone. */
		readonly phone: string | null;
	};
	readonly contract: {
		readonly orderNumber: string;
		/** Server-verified ownership only. Never taken from the client. */
		readonly saleorOrderId: string | null;
		readonly saleorCustomerId: string | null;
	};
	readonly scope: WithdrawalScope;
	readonly items: readonly WithdrawalItem[];
	readonly note: string | null;
	/** The exact text the customer confirmed, rendered server-side. */
	readonly noticeSnapshot: string;
	readonly legalNoticeVersion: string;
	readonly privacyNoticeVersion: string;
}

/** What the server returns once the record is durable. */
export interface WithdrawalAccepted {
	readonly submissionId: string;
	readonly submissionNumber: string;
	/** ISO 8601, generated by the server — never by the browser. */
	readonly submittedAt: string;
	readonly orderMatchStatus: OrderMatchStatus;
	/** True when this submissionId already existed and the original was returned. */
	readonly duplicate: boolean;
}

/**
 * Field limits.
 *
 * These bound abuse, not the customer. Every value is far above what a real notice
 * needs, because a limit that truncates a legal submission is worse than a large one.
 */
export const WITHDRAWAL_LIMITS = {
	name: 120,
	email: 254,
	orderNumber: 64,
	phone: 40,
	note: 2_000,
	productName: 300,
	items: 50,
	quantityPerItem: 999,
	/** Rejected before parsing; a real notice is a couple of kilobytes. */
	bodyBytes: 64 * 1024,
} as const;

/**
 * Versions stamped onto every record so a submission can be replayed against the copy
 * that was actually shown.
 *
 * ## Deploy gate
 *
 * `LEGAL_COPY_APPROVED` is `false` and must stay `false` until the reviewed Slovak
 * legal-content artifact is delivered. The functional flow is complete without it —
 * this flag exists so "the form works" cannot be mistaken for "the wording is signed
 * off". `assertLegalCopyApprovedForProduction` is the check a deploy step can call.
 */
export const LEGAL_COPY_APPROVED = false;
export const LEGAL_NOTICE_VERSION = "sk-withdrawal-DRAFT-2026-07-30";
export const PRIVACY_NOTICE_VERSION = "sk-privacy-DRAFT-2026-07-30";

export function assertLegalCopyApprovedForProduction(): void {
	if (!LEGAL_COPY_APPROVED) {
		throw new Error(
			"Withdrawal legal copy is still a draft. Supply the approved Slovak legal-content " +
				"artifact, set LEGAL_COPY_APPROVED and bump the notice versions before deploying.",
		);
	}
}
