/**
 * The withdrawal submission contract, as Payload defines it.
 *
 * One legal process, one backend contract, two UX modes. A guest and a signed-in
 * customer submit the *same* body to the *same* endpoint and produce the same kind of
 * record; `source` only says which path filled the fields in. Registration must never
 * be a condition of exercising the right, so nothing here may depend on a session.
 *
 * ## Payload owns the record, not the storefront
 *
 * The endpoint rejects unknown keys at the top level and inside nested objects, so the
 * allowlist below is exact rather than indicative: one extra field is a 400, not a
 * tolerated addition. Three things that used to be assembled here are now generated by
 * the server that stores them — `submittedAt`, `submissionNumber` and the canonical
 * `noticeSnapshot`. That is the right split. When the request, the database and the
 * confirmation e-mail each build their own version of the notice, they eventually
 * disagree, and the one thing this feature exists to produce is a record nobody can
 * argue with.
 */

export const WITHDRAWAL_CONTRACT_VERSION = 2;

/** V2 is SK-only. Other markets fall through to the route's not-launched behaviour. */
export const WITHDRAWAL_MARKET = "SK";
export const WITHDRAWAL_LOCALE = "sk";

export type WithdrawalSource = "guest" | "account";
export type WithdrawalScope = "wholeOrder" | "selectedItems";
export type WithdrawalReturnMethod = "merchantPickup";

export interface WithdrawalCustomerOrderItem {
	readonly name: string;
	readonly quantity: number;
}

/**
 * The exact declaration shown above the final button and signed in the V2 raw body.
 * Keep this pure and shared by the client preview and server submission so the CMS
 * persists exactly what the customer saw.
 */
export function withdrawalCustomerStatement(orderNumber: string, scope: WithdrawalScope): string {
	const normalizedOrderNumber = orderNumber
		.replace(/[\u0000-\u001f\u007f-\u009f]/g, " ")
		.replace(/\s+/g, " ")
		.trim();
	const range = scope === "wholeOrder" ? "v celom rozsahu" : "v rozsahu uvedených položiek";
	return `Odstupujem od zmluvy k objednávke ${normalizedOrderNumber} ${range}.`;
}

export interface WithdrawalItem {
	/** Saleor order line id, or `null` when the customer described the item by hand. */
	readonly orderLineId: string | null;
	readonly productName: string;
	/**
	 * Optional for manually entered items. Account lines keep it `null` because the
	 * current Saleor order query does not request `sku`; `orderLineId` plus
	 * `productName` identify those items.
	 */
	readonly sku: string | null;
	readonly quantity: number;
}

/**
 * The request body, exactly.
 *
 * Every key here is on Payload's allowlist and nothing else is. The vendored provider
 * pack remains the immutable V1 base schema; the V2 conformance test validates that base
 * projection and then pins the four V2 additions exactly. Note what is still absent:
 * `noticeSnapshot`, `submittedAt`, `submissionNumber` and `emailDelivery`, all of which
 * the server builds and all of which the endpoint rejects in a create request.
 *
 * `customer.phone` was absent too, until contract revision `1.1.0` made it optional and
 * nullable. It is sent as an explicit `null` rather than omitted, so the body has one
 * canonical shape — the endpoint accepts both, and one shape is easier to reason about
 * than two.
 */
export interface WithdrawalSubmission {
	readonly submissionId: string;
	readonly experienceVersion: "returns-v2";
	readonly customerStatement: string;
	/** Customer-safe order summary. Populated only for a verified whole order. */
	readonly customerOrderItems: readonly WithdrawalCustomerOrderItem[];
	readonly returnMethod: WithdrawalReturnMethod;
	readonly source: WithdrawalSource;
	readonly market: typeof WITHDRAWAL_MARKET;
	readonly locale: typeof WITHDRAWAL_LOCALE;
	readonly customer: {
		readonly name: string;
		readonly email: string;
		/** Optional. `null` when the customer left it blank — never omitted. */
		readonly phone: string | null;
	};
	readonly contract: {
		readonly orderNumber: string;
		/** Server-verified ownership only. Never taken from the client. */
		readonly saleorOrderId: string | null;
		readonly saleorCustomerId: string | null;
	};
	readonly scope: WithdrawalScope;
	/** Empty for `wholeOrder`; 1–100 entries for `selectedItems`. */
	readonly items: readonly WithdrawalItem[];
	readonly note: string | null;
	readonly legalNoticeVersion: string;
	readonly privacyNoticeVersion: string;
}

/** Customer-safe V2 acknowledgement returned once the immutable artifacts are ready. */
export interface WithdrawalV2Accepted {
	readonly submissionNumber: string;
	/** True when this submissionId already existed and the original was returned. */
	readonly duplicate: boolean;
	/** Complete A4 receipt rendered and escaped by the versioned CMS renderer. */
	readonly printConfirmationHTML: string;
	/** Minimal print-ready parcel slip; null only when no slip artifact exists. */
	readonly parcelSlipHTML: string | null;
}

/**
 * Field limits.
 *
 * These bound abuse, not the customer, and every one sits at or under Payload's own
 * limit so a notice this side accepts can never be refused for length on the other.
 */
export const WITHDRAWAL_LIMITS = {
	name: 120,
	email: 254,
	/**
	 * Payload's own ceiling, matched exactly rather than undercut.
	 *
	 * Measured in **Unicode code points of the trimmed value**, not in `String.length`.
	 * Every phone fixture the provider ships is BMP-only, so a `.length` implementation
	 * passes the entire vendored set and is still wrong; only an astral character shows
	 * the difference. `validate.ts` counts code points and a test pins it.
	 */
	phoneCodePoints: 32,
	orderNumber: 128,
	note: 2_000,
	customerStatement: 2_000,
	productName: 300,
	items: 100,
	quantityPerItem: 999,
	/** Payload rejects above 64 KiB, so the same ceiling is checked before sending. */
	bodyBytes: 64 * 1024,
} as const;

/** Payload accepts a 10–11 digit Unix timestamp in SECONDS. Milliseconds are rejected. */
export function formsTimestampSeconds(nowMs: number = Date.now()): string {
	return String(Math.floor(nowMs / 1000));
}

/**
 * Versions stamped onto every record so a submission can be replayed against the copy
 * that was actually shown.
 *
 * ## Deploy gate
 *
 * The flag records that the currently versioned Slovak declaration may be served. The
 * 2026-08-02 authorization to activate storefront V2 is operational approval, not a
 * claim of final Outlook/Gmail visual acceptance. The §15(1)(g) checkout/VOP evidence,
 * RBAC and real-client visual evidence remain separate release gates.
 *
 * `isWithdrawalFormServable()` below is what actually enforces this on the request path.
 */
export const LEGAL_COPY_APPROVED = true;

/**
 * Versions stamped onto every stored record, permanently.
 *
 * These match the published SK/sk V2 CMS bundle. They identify the immutable copy shown
 * with the submitted declaration and must not be changed independently of that bundle.
 */
export const LEGAL_NOTICE_VERSION = "withdrawal-sk-v2";
export const PRIVACY_NOTICE_VERSION = "privacy-sk-v1";

export function assertLegalCopyApprovedForProduction(): void {
	if (!LEGAL_COPY_APPROVED) {
		throw new Error(
			"Withdrawal legal copy is not enabled for production. Approve the versioned Slovak " +
				"declaration, set LEGAL_COPY_APPROVED and publish the matching CMS bundle first.",
		);
	}
}

/**
 * The other precondition, and the one the copy approval does not cover.
 *
 * The production Payload endpoint and published SK/sk V2 bundle are live. This flag is
 * the storefront-side activation interlock: it remains off until backend readiness has
 * succeeded, and is switched on only for the storefront release that speaks V2.
 *
 * Approving the copy and standing the backend up are different claims, so they get
 * different flags. Keeping both conditions executable prevents a production build from
 * exposing the form before its matching backend experience is ready.
 *
 * It is an ENVIRONMENT flag, not a source constant, and read at call time. A constant
 * keyed off `NODE_ENV` would have made the form unreachable in every production-mode
 * build — staging and the CLAUDE.md §13 spare-port verification build included — so the
 * signed live matrix this flag's own release gate demands could not have been run without
 * first shipping a code change to disable the gate. Set `WITHDRAWAL_BACKEND_LIVE=true` in
 * the environment only after backend readiness succeeds; it is a sequencing interlock,
 * not a claim about final visual acceptance.
 */
export function isWithdrawalBackendLive(): boolean {
	return process.env.WITHDRAWAL_BACKEND_LIVE === "true";
}

/**
 * Whether the ONLINE FUNCTION may be offered in this process.
 *
 * Not whether the page may be served — that distinction cost a review round. The page is
 * a legally required disclosure, live since the legal-pages release and listed in the
 * sitemap; only the form section is behind this. When it returns false the route still
 * renders the deadlines, the e-mail and postal routes and the model-form link, and logs
 * `[withdrawal] online-function-off` with `withdrawalBlockReason()` so the absence has an
 * explanation.
 *
 * Both preconditions, and development is exempt from both because that is where the form
 * is exercised.
 */
export function isWithdrawalFormServable(): boolean {
	if (process.env.NODE_ENV !== "production") return true;
	return LEGAL_COPY_APPROVED && isWithdrawalBackendLive();
}

/** Why the form is not being served, for the log line. `null` when it is. */
export function withdrawalBlockReason(): string | null {
	if (isWithdrawalFormServable()) return null;
	if (!LEGAL_COPY_APPROVED) return "LEGAL_COPY_APPROVED is false";
	return 'WITHDRAWAL_BACKEND_LIVE is not "true" — storefront V2 activation is disabled';
}
