/**
 * The withdrawal submission contract, as Payload defines it.
 *
 * One legal process, one backend contract, two UX modes. A guest and a signed-in
 * customer submit the *same* body to the *same* endpoint and produce the same kind of
 * record; `source` only says which path filled the fields in. Registration must never
 * be a condition of exercising the right, so nothing here may depend on a session.
 *
 * ## Payload owns the record, not the storefront
 *
 * The endpoint rejects unknown keys at the top level and inside nested objects, so the
 * allowlist below is exact rather than indicative: one extra field is a 400, not a
 * tolerated addition. Three things that used to be assembled here are now generated by
 * the server that stores them — `submittedAt`, `submissionNumber` and the canonical
 * `noticeSnapshot`. That is the right split. When the request, the database and the
 * confirmation e-mail each build their own version of the notice, they eventually
 * disagree, and the one thing this feature exists to produce is a record nobody can
 * argue with.
 */

export const WITHDRAWAL_CONTRACT_VERSION = 1;

/** V1 is SK-only. Other markets fall through to the route's not-launched behaviour. */
export const WITHDRAWAL_MARKET = "SK";
export const WITHDRAWAL_LOCALE = "sk";

export type WithdrawalSource = "guest" | "account";
export type WithdrawalScope = "wholeOrder" | "selectedItems";

/**
 * How the CMS matched the submission to a real order. Advisory only.
 *
 * None of these values may block a submission. A customer who mistypes an order
 * number, ordered under a different e-mail, or is withdrawing before delivery still
 * gave a legally effective notice; the mismatch is an internal review state, not a
 * rejection. The storefront never computes this — the server owns it.
 */
export type OrderMatchStatus = "pending" | "matched" | "notFound" | "emailMismatch" | "manualReview";

export interface WithdrawalItem {
	/** Saleor order line id, or `null` when the customer described the item by hand. */
	readonly orderLineId: string | null;
	readonly productName: string;
	/**
	 * Approved as always-`null` for V1. The order query's variant selection does not
	 * request `sku` and changing a Saleor GraphQL document needs sign-off (CLAUDE.md
	 * §10). `orderLineId` plus `productName` identify the item.
	 */
	readonly sku: string | null;
	readonly quantity: number;
}

/**
 * The request body, exactly.
 *
 * Every key here is on Payload's allowlist and nothing else is. Note what is absent:
 * `customer.phone` (accepted by the contact endpoint, not by this one), and
 * `noticeSnapshot`, which the server builds from these fields.
 */
export interface WithdrawalSubmission {
	readonly submissionId: string;
	readonly source: WithdrawalSource;
	readonly market: typeof WITHDRAWAL_MARKET;
	readonly locale: typeof WITHDRAWAL_LOCALE;
	readonly customer: {
		readonly name: string;
		readonly email: string;
	};
	readonly contract: {
		readonly orderNumber: string;
		/** Server-verified ownership only. Never taken from the client. */
		readonly saleorOrderId: string | null;
		readonly saleorCustomerId: string | null;
	};
	readonly scope: WithdrawalScope;
	/** Empty for `wholeOrder`; 1–100 entries for `selectedItems`. */
	readonly items: readonly WithdrawalItem[];
	readonly note: string | null;
	readonly legalNoticeVersion: string;
	readonly privacyNoticeVersion: string;
}

/**
 * The canonical snapshot, built and stored by Payload from the normalised submission.
 *
 * Structured rather than prose. The storefront renders a human-readable notice *from*
 * this — deterministically, as a pure function of what was stored — instead of keeping
 * its own copy of the text. That is what makes the receipt, the record and the
 * confirmation e-mail incapable of drifting apart.
 */
export interface PayloadNoticeSnapshot {
	readonly schemaVersion: number;
	readonly source: WithdrawalSource;
	readonly market: string;
	readonly locale: string;
	readonly customer: { readonly name: string; readonly email: string };
	readonly contract: { readonly orderNumber: string };
	readonly scope: WithdrawalScope;
	readonly items: readonly WithdrawalItem[];
	readonly note: string | null;
	readonly legalNoticeVersion: string;
	readonly privacyNoticeVersion: string;
}

export type EmailDeliveryStatus = "pending" | "sent" | "failed";

/**
 * Delivery state, when the endpoint reports it.
 *
 * Optional on purpose: Payload owns sending in V1, but the create response does not
 * carry these fields yet. Absent must therefore mean "not known", never "failed" —
 * telling a customer their confirmation failed when it is merely unreported would be
 * its own small lie.
 */
export interface EmailDeliveryState {
	readonly customerStatus: EmailDeliveryStatus;
	readonly internalStatus: EmailDeliveryStatus;
}

/** What the server returns once the record is durable. */
export interface WithdrawalAccepted {
	/** Payload record id. Distinct from `submissionId`, and the key the delivery seam uses. */
	readonly id: string;
	readonly submissionId: string;
	readonly submissionNumber: string;
	/** ISO 8601, generated by the server — never by the browser, never by us. */
	readonly submittedAt: string;
	readonly noticeSnapshot: PayloadNoticeSnapshot;
	readonly orderMatchStatus: OrderMatchStatus;
	/** True when this submissionId already existed and the original was returned. */
	readonly duplicate: boolean;
	readonly emailDelivery: EmailDeliveryState | null;
}

/**
 * Field limits.
 *
 * These bound abuse, not the customer, and every one sits at or under Payload's own
 * limit so a notice this side accepts can never be refused for length on the other.
 */
export const WITHDRAWAL_LIMITS = {
	name: 120,
	email: 254,
	orderNumber: 128,
	note: 2_000,
	productName: 300,
	items: 100,
	quantityPerItem: 999,
	/** Payload rejects above 64 KiB, so the same ceiling is checked before sending. */
	bodyBytes: 64 * 1024,
} as const;

/** Payload accepts a 10–11 digit Unix timestamp in SECONDS. Milliseconds are rejected. */
export function formsTimestampSeconds(nowMs: number = Date.now()): string {
	return String(Math.floor(nowMs / 1000));
}

/**
 * Versions stamped onto every record so a submission can be replayed against the copy
 * that was actually shown.
 *
 * ## Deploy gate
 *
 * `LEGAL_COPY_APPROVED` is `false` and must stay `false` until the reviewed Slovak
 * legal-content artifact is delivered. The functional flow is complete without it —
 * this flag exists so "the form works" cannot be mistaken for "the wording is signed
 * off". `assertLegalCopyApprovedForProduction` is the check a deploy step can call.
 */
export const LEGAL_COPY_APPROVED = false;
export const LEGAL_NOTICE_VERSION = "withdrawal-sk-2026-07-30-v0-DRAFT";
export const PRIVACY_NOTICE_VERSION = "privacy-sk-2026-07-30-v0-DRAFT";

export function assertLegalCopyApprovedForProduction(): void {
	if (!LEGAL_COPY_APPROVED) {
		throw new Error(
			"Withdrawal legal copy is still a draft. Supply the approved Slovak legal-content " +
				"artifact, set LEGAL_COPY_APPROVED and bump the notice versions before deploying.",
		);
	}
}
