/**
 * German copy for the online withdrawal function — PREPARED, NOT WIRED.
 *
 * Nothing imports this yet, and that is correct. Returns V2 pins `market: "SK"` and
 * `locale: "sk"` as literal types (`contract.ts`), so the Payload endpoint rejects a
 * notice submitted from `/de` or `/at`. Rendering the form on those markets would offer
 * a customer a button that cannot produce a legal record — the one outcome the whole
 * feature exists to prevent. `servesOnlineFunction()` in the withdrawal route therefore
 * keeps the form Slovak-only, and the German pages render the "preview not activated"
 * notice instead.
 *
 * ## Why it is here anyway
 *
 * For Germany the missing online function is a SALES blocker, not a missing convenience:
 * § 356a BGB has required an online withdrawal function since 2026-06-19, and § 356a(4)
 * governs what the acknowledgement must contain — the declaration itself plus the date
 * and time of RECEIPT. So DE cannot open to paid consumer sales until Returns V2 accepts
 * it, and when that lands the copy should not be the thing holding it up.
 *
 * ## What the owner of Returns V2 needs to know before using this
 *
 * 1. **The form's strings currently live inline in `withdrawal-form.tsx` JSX.** Wiring a
 *    second language means extracting them into a copy map first. That file is the
 *    Returns V2 surface, so that extraction is deliberately NOT done here — doing it
 *    would have collided with parallel work on the same component.
 * 2. **`receivedAt` does not exist yet.** `submittedAt` is generated by Payload when the
 *    record is saved. That is close to receipt but is not the same event, and the Slovak
 *    § 20a(5) notice correctly describes the time of SENDING. German needs receipt as
 *    well, which is why `receivedTimeLabel` is here and why both labels appear in the
 *    confirmation e-mail template. Do NOT rename the existing field and do NOT mint a
 *    second timestamp in the storefront — a client clock is not evidence. This is a
 *    server-side contract change owned by Returns V2.
 * 3. **Never submit `de`/`at` as `market: "SK"`.** It would write a legal record naming
 *    the wrong market.
 *
 * Source: the delivered package, `data/ui.de-DE.json` and `data/ui.de-AT.json`, which are
 * byte-identical for these keys — the German and Austrian forms differ only in the page
 * headings around them, not in the controls. The two button labels stay `Vertrag
 * widerrufen` / `Widerruf bestätigen` in BOTH markets even though Austrian law calls the
 * right a *Rücktritt*: they are bound to the contract, and the Austrian page explains the
 * mismatch in prose.
 */

export interface WithdrawalFieldCopy {
	readonly label: string;
	readonly help?: string;
	readonly requiredError?: string;
	readonly invalidError?: string;
}

export interface WithdrawalCopy {
	readonly entryLabel: string;
	readonly formTitle: string;
	readonly intro: string;
	readonly fullName: WithdrawalFieldCopy;
	readonly email: WithdrawalFieldCopy;
	readonly contractReference: WithdrawalFieldCopy;
	readonly scopeLabel: string;
	readonly scopeWhole: string;
	readonly scopePartial: string;
	readonly itemsLabel: string;
	readonly itemsHelp: string;
	readonly itemsRequiredError: string;
	readonly pickupInterest: string;
	readonly pickupHelp: string;
	readonly noteLabel: string;
	readonly privacyNotice: string;
	readonly reviewButton: string;
	readonly reviewTitle: string;
	readonly declarationWhole: string;
	readonly declarationPartial: string;
	readonly finalExplanation: string;
	readonly editButton: string;
	readonly submitButton: string;
	readonly submitting: string;
	readonly acceptedTitle: string;
	readonly acceptedBody: string;
	readonly receiptNumberLabel: string;
	/** Time the declaration was SENT. Today's `submittedAt`. */
	readonly submissionTimeLabel: string;
	/** Time the declaration was RECEIVED — § 356a(4) BGB. No backend field yet. */
	readonly receivedTimeLabel: string;
	readonly saveReceipt: string;
	readonly emailIssue: string;
	readonly failedTitle: string;
	readonly failedBody: string;
	readonly unknownTitle: string;
	readonly unknownBody: string;
	readonly rateLimit: string;
	readonly unavailable: string;
	readonly noScript: string;
}

export const WITHDRAWAL_COPY_DE: WithdrawalCopy = {
	entryLabel: "Vertrag widerrufen",
	formTitle: "Online-Widerruf",
	intro: "Sie können den Widerruf auch ohne Kundenkonto absenden. Einen Grund müssen Sie nicht angeben.",
	fullName: {
		label: "Vor- und Nachname",
		help: "Geben Sie den Namen der Person an, die den Kauf widerruft.",
		requiredError: "Bitte geben Sie Ihren Vor- und Nachnamen an.",
	},
	email: {
		label: "E-Mail-Adresse für die Bestätigung",
		help: "An diese Adresse senden wir eine Kopie Ihrer Erklärung und die Eingangsbestätigung.",
		requiredError: "Bitte geben Sie eine E-Mail-Adresse für die Bestätigung an.",
		invalidError: "Bitte prüfen Sie die Schreibweise der E-Mail-Adresse.",
	},
	contractReference: {
		label: "Bestellnummer oder andere Angaben zum Kauf",
		help: "Die Bestellnummer finden Sie in Ihrer Bestellbestätigung. Haben Sie sie nicht zur Hand, beschreiben Sie den Kauf, zum Beispiel mit Artikelbezeichnung und ungefährem Bestelldatum.",
		requiredError: "Bitte machen Sie Angaben, mit denen wir den Kauf zuordnen können.",
	},
	scopeLabel: "Was möchten Sie widerrufen?",
	scopeWhole: "Die gesamte Bestellung",
	scopePartial: "Nur bestimmte Artikel",
	itemsLabel: "Betroffene Artikel und Stückzahl",
	itemsHelp:
		"Geben Sie die Bezeichnung oder Artikelnummer und die Stückzahl an. Die Bezeichnung muss nicht genau dem Katalog entsprechen, aber es muss erkennbar sein, welche Artikel gemeint sind.",
	itemsRequiredError: "Bitte geben Sie an, welche Artikel und Stückzahlen der Widerruf umfasst.",
	pickupInterest: "Ich möchte ein Preisangebot für eine Abholung erhalten",
	pickupHelp:
		"Dies ist nur eine Anfrage. Eine kostenpflichtige Abholung beauftragen wir erst, wenn Sie dem Preis ausdrücklich zugestimmt haben.",
	noteLabel: "Zusätzliche Nachricht (optional)",
	privacyNotice:
		"Wir verwenden Ihre Angaben zur Annahme und Bearbeitung des Widerrufs sowie zur Erfüllung gesetzlicher Pflichten. Einzelheiten finden Sie in unseren Datenschutzhinweisen.",
	reviewButton: "Angaben prüfen",
	reviewTitle: "Prüfen Sie Ihre Erklärung",
	declarationWhole: "Hiermit widerrufe ich den nachfolgend bezeichneten Kaufvertrag in vollem Umfang.",
	declarationPartial:
		"Hiermit widerrufe ich den nachfolgend bezeichneten Kaufvertrag hinsichtlich der genannten Artikel und Stückzahlen.",
	finalExplanation:
		"Mit der folgenden Schaltfläche senden Sie eine Widerrufserklärung ab. Sie stellen damit nicht nur eine Anfrage an den Kundenservice.",
	editButton: "Angaben ändern",
	submitButton: "Widerruf bestätigen",
	submitting: "Die Erklärung wird übermittelt …",
	acceptedTitle: "Ihre Widerrufserklärung ist eingegangen",
	acceptedBody:
		"Wir senden Ihnen die Eingangsbestätigung mit Ihrer Erklärung sowie Versand- und Eingangszeitpunkt an die angegebene E-Mail-Adresse. Über das weitere Vorgehen informieren wir Sie.",
	receiptNumberLabel: "Vorgangsnummer",
	submissionTimeLabel: "Datum und Uhrzeit des Versands",
	receivedTimeLabel: "Datum und Uhrzeit des Eingangs",
	saveReceipt: "Bestätigung speichern",
	emailIssue:
		"Ihre Erklärung wurde gespeichert. Die Bestätigung konnte bisher jedoch nicht per E-Mail versendet werden. Wir versuchen den Versand erneut. Sie können die Bestätigung auch hier speichern; Ihr Widerruf bleibt als eingegangen erfasst.",
	failedTitle: "Die Erklärung konnte nicht entgegengenommen werden",
	failedBody:
		"Versuchen Sie es erneut oder senden Sie Ihre Erklärung an info@maky.store. Ihre Eingaben bleiben im Formular erhalten.",
	unknownTitle: "Das Ergebnis der Übermittlung konnte nicht bestätigt werden",
	unknownBody:
		"Wir konnten nicht zuverlässig feststellen, ob Ihre Erklärung eingegangen ist. Prüfen Sie die Bestätigungs-E-Mail oder den Status des Vorgangs. Bei einer Wiederholung verwenden wir dieselbe Kennung, um einen doppelten Vorgang zu vermeiden. Sie können Ihren Widerruf auch an info@maky.store senden.",
	rateLimit:
		"Die Übermittlung ist vorübergehend eingeschränkt. Versuchen Sie es später erneut oder senden Sie Ihre Erklärung an info@maky.store.",
	unavailable:
		"Die Online-Übermittlung ist derzeit nicht verfügbar. Sie können Ihre Erklärung an info@maky.store oder per Post senden. Wir arbeiten daran, die Online-Funktion wiederherzustellen.",
	noScript:
		"Für die interaktive Funktion ist JavaScript erforderlich. Sie können Ihre Erklärung auch an info@maky.store senden oder das Formular zum Ausdrucken verwenden.",
};

/**
 * Austria uses the same form copy as Germany.
 *
 * Exported separately rather than aliased so that a future Austrian-only divergence has
 * an obvious place to go, and so a reader does not have to check whether `deAt` was
 * simply forgotten.
 */
export const WITHDRAWAL_COPY_DE_AT: WithdrawalCopy = WITHDRAWAL_COPY_DE;
