import { type WithdrawalCopy } from "./copy-de";

/**
 * Polish copy for the online withdrawal function — PREPARED, NOT WIRED.
 *
 * Nothing imports this, and that is correct. Returns V2 pins `market: "SK"` and
 * `locale: "sk"` as literal types (`contract.ts`), so the Payload endpoint rejects a
 * notice submitted from `/pl`. Rendering the form there would offer a customer a button
 * that cannot produce a legal record — the one outcome the feature exists to prevent.
 * `servesOnlineFunction()` keeps the form Slovak-only, and `/pl/odstupenie-od-zmluvy`
 * renders the "preview not activated" notice instead.
 *
 * ## Provenance — every string here is the delivered editorial value, verbatim
 *
 * Source: `data/ui.pl-PL.json` from the delivered PL/HU package (`schema
 * maky-editorial-ui/1`, `locale pl-PL`). The first version of this file was written
 * before that JSON reached the machine and paraphrased it from the Slovak and German
 * copy; 21 of the 38 strings drifted. They have been replaced wholesale rather than
 * patched, so the file now matches the approved export field for field.
 *
 * Two of those drifts were not synonyms and are the reason this was worth redoing:
 *
 * 1. `acceptedBody` promised the customer both the time of SENDING and the time of
 *    RECEIPT. Only one of those is evidenced. The approved text names the sending time
 *    alone, which is also what the Hungarian statute asks for (45/2014 § 22(1c), "a
 *    megküldés napját és időpontját"). `receivedTimeLabel` stays as a dormant label for
 *    the day R has a real receipt event — it must NOT be filled with a copy of
 *    `submittedAt`, which is the time of the database write and a third event again.
 * 2. `unknownBody` told the customer to check "stan sprawy". There is no customer-facing
 *    case-status view in this implementation, so it pointed at something that does not
 *    exist. The approved text says: check your mail, a retry reuses the same identifier
 *    so no duplicate is created, and e-mail remains open.
 *
 * `privacyHref` (`/pl/ochrana-osobnych-udajov`) and the `formExtras` block are in the
 * delivered JSON but not in `WithdrawalCopy`. They are recorded in the R handoff rather
 * than bolted onto a shared type this thread does not own.
 *
 * ## What the owner of Returns V2 needs to know before using this
 *
 * 1. The form's strings still live inline in `withdrawal-form.tsx` JSX. Wiring a second
 *    language means extracting them into a copy map first. That file is the Returns V2
 *    surface, so the extraction is deliberately not done here.
 * 2. There is no `receivedAt`. `submittedAt` is generated by Payload when the record is
 *    saved. Do not mint a second timestamp in the storefront; a client clock is not
 *    evidence. This is a server-side contract change owned by R.
 * 3. **Never submit `pl` as `market: "SK"`.** It would write a legal record naming the
 *    wrong market.
 * 4. Poland's transposition of the online-function duty is deliberately left open by the
 *    package — that is not a finding that e-mail always suffices there.
 */
export const WITHDRAWAL_COPY_PL: WithdrawalCopy = {
	entryLabel: "Odstąp od umowy",
	formTitle: "Odstąpienie od umowy online",
	intro: "Oświadczenie można wysłać bez konta klienta. Nie trzeba podawać przyczyny.",
	fullName: {
		label: "Imię i nazwisko",
		help: "Prosimy podać imię i nazwisko osoby, która odstępuje od umowy.",
		requiredError: "Prosimy podać imię i nazwisko.",
	},
	email: {
		label: "Adres e-mail do potwierdzenia",
		help: "Na ten adres wyślemy kopię oświadczenia i potwierdzenie jego otrzymania.",
		requiredError: "Prosimy podać adres e-mail do potwierdzenia.",
		invalidError: "Prosimy sprawdzić poprawność adresu e-mail.",
	},
	contractReference: {
		label: "Numer zamówienia lub inne dane zakupu",
		help: "Numer jest w potwierdzeniu zamówienia. Jeśli nie jest dostępny, prosimy opisać zakup tak, aby można było go odnaleźć, na przykład podając produkt i przybliżoną datę.",
		requiredError: "Prosimy podać dane pozwalające zidentyfikować zakup.",
	},
	scopeLabel: "Czego dotyczy odstąpienie?",
	scopeWhole: "Całego zamówienia",
	scopePartial: "Tylko wybranych produktów",
	itemsLabel: "Produkty i liczba sztuk",
	itemsHelp:
		"Prosimy podać nazwę lub kod produktu oraz liczbę sztuk. Opis nie musi być identyczny z nazwą w katalogu, ale powinien jednoznacznie wskazywać produkty.",
	itemsRequiredError: "Prosimy wskazać produkty i liczbę sztuk objętych odstąpieniem.",
	pickupInterest: "Chcę otrzymać wycenę odbioru towaru",
	pickupHelp: "To tylko zapytanie o ofertę. Płatny odbiór zamówimy dopiero po wyraźnym zaakceptowaniu ceny.",
	noteLabel: "Dodatkowa wiadomość (opcjonalnie)",
	privacyNotice:
		"Dane wykorzystamy do przyjęcia i obsługi odstąpienia oraz wykonania obowiązków prawnych. Szczegóły znajdują się w Polityce prywatności.",
	reviewButton: "Sprawdź dane",
	reviewTitle: "Prosimy sprawdzić oświadczenie",
	declarationWhole: "Niniejszym odstępuję w całości od wskazanej poniżej umowy sprzedaży.",
	declarationPartial:
		"Niniejszym odstępuję od wskazanej poniżej umowy sprzedaży w zakresie wymienionych produktów i liczby sztuk.",
	finalExplanation:
		"Użycie poniższego przycisku oznacza wysłanie oświadczenia o odstąpieniu od umowy, a nie tylko pytania do obsługi klienta.",
	editButton: "Popraw dane",
	submitButton: "Potwierdź odstąpienie od umowy",
	submitting: "Wysyłanie oświadczenia…",
	acceptedTitle: "Otrzymaliśmy oświadczenie o odstąpieniu",
	acceptedBody:
		"Potwierdzenie wraz z treścią oświadczenia i datą oraz godziną jego wysłania przesyłamy na podany adres e-mail. Poinformujemy o dalszym postępowaniu.",
	receiptNumberLabel: "Numer zgłoszenia",
	submissionTimeLabel: "Data i godzina wysłania",
	receivedTimeLabel: "Data i godzina otrzymania",
	saveReceipt: "Zapisz potwierdzenie",
	emailIssue:
		"Oświadczenie zostało zapisane, ale nie udało się jeszcze wysłać potwierdzenia e-mailem. Ponowimy wysyłkę. Potwierdzenie można zapisać także tutaj; zgłoszenie pozostaje przyjęte.",
	failedTitle: "Nie udało się przyjąć oświadczenia",
	failedBody:
		"Prosimy spróbować ponownie lub wysłać oświadczenie na info@maky.store. Wpisane dane pozostają w formularzu.",
	unknownTitle: "Nie udało się potwierdzić wyniku wysyłki",
	unknownBody:
		"Nie możemy wiarygodnie ustalić, czy oświadczenie zostało przyjęte. Prosimy sprawdzić pocztę. Przy ponowieniu użyjemy tego samego identyfikatora, aby uniknąć podwójnego zgłoszenia. Oświadczenie można również wysłać na info@maky.store.",
	rateLimit:
		"Wysyłanie jest tymczasowo ograniczone. Prosimy spróbować później lub przesłać oświadczenie na info@maky.store.",
	unavailable:
		"Wysyłanie online jest obecnie niedostępne. Oświadczenie można przesłać na info@maky.store lub pocztą. Pracujemy nad przywróceniem tej funkcji.",
	noScript:
		"Interaktywna część wymaga JavaScript. Oświadczenie można również wysłać na info@maky.store lub skorzystać z formularza do wydrukowania.",
};
