import { type WithdrawalCopy } from "./copy-de";

/**
 * Italian copy for the online withdrawal function — PREPARED, NOT WIRED.
 *
 * Nothing imports this, and that is correct. Returns V2 pins `market: "SK"` and
 * `locale: "sk"` as literal types (`contract.ts`), so the Payload endpoint rejects a
 * notice submitted from `/it`. Rendering the form there would offer a customer a button
 * that cannot produce a legal record — the one outcome the feature exists to prevent.
 * `servesOnlineFunction()` keeps the form Slovak-only, and `/it/odstupenie-od-zmluvy`
 * renders the "preview not activated" notice instead.
 *
 * ## Why the gap matters more here than for de/at
 *
 * Italy has required an online withdrawal function since 19 June 2026: D.lgs. 209/2025
 * inserted article 54-bis into the Codice del consumo, and its article 4 sets that date.
 * The requirement is a function that is easy to find and continuously available while the
 * period runs, identifying the consumer and the contract, with an acknowledgement on a
 * durable medium carrying the notice and the date and time it was SENT.
 *
 * So the preview state is a gap to be closed, not a settled position — the delivered
 * package says it plainly: a static preview is not a lawful permanent substitute for the
 * function. It is also not something `noindex` resolves; the duty attaches to serving
 * Italian consumers, not to being indexed.
 *
 * ## The two control labels are a compliance artefact
 *
 * `entryLabel` and `submitButton` are the unambiguous wordings the delivered legal
 * research settled on for article 54-bis — *Recedere dal contratto qui* and *Conferma
 * recesso*. Do not reword either for fluency.
 *
 * ## Provenance
 *
 * Every string is the delivered editorial value, verbatim, from `data/ui.it-IT.json`
 * (`schema maky-editorial-ui/1`, `locale it-IT`) in the IT/FR package. This file was
 * generated from that JSON rather than transcribed, precisely because the Polish file had
 * to be rewritten once when a hand-written first draft drifted from the approved export
 * in 21 of 38 strings.
 *
 * `privacyHref` (`/it/ochrana-osobnych-udajov`) and the `formExtras` block are in the
 * delivered JSON but not in `WithdrawalCopy`. They are recorded in the R handoff rather
 * than bolted onto a shared type this thread does not own.
 *
 * ## What the owner of Returns V2 needs to know before using this
 *
 * 1. The form's strings still live inline in `withdrawal-form.tsx` JSX. Wiring a second
 *    language means extracting them into a copy map first. That file is the Returns V2
 *    surface, so the extraction is deliberately not done here.
 * 2. There is no `receivedAt`. `submittedAt` is generated by Payload when the record is
 *    saved, which is a third event again — neither sending nor receipt. `acceptedBody`
 *    below names the sending time only, and `receivedTimeLabel` must NOT be filled with a
 *    copy of `submittedAt`. Do not mint a second timestamp in the storefront; a client
 *    clock is not evidence.
 * 3. **Never submit `it` as `market: "SK"`.** It would write a legal record naming the
 *    wrong market.
 */
export const WITHDRAWAL_COPY_IT: WithdrawalCopy = {
	entryLabel: "Recedere dal contratto qui",
	formTitle: "Recesso online",
	intro: "Puoi inviare la dichiarazione senza un account cliente. Non è necessario indicare il motivo.",
	fullName: {
		label: "Nome e cognome",
		help: "Indica il nome della persona che recede dal contratto.",
		requiredError: "Inserisci nome e cognome.",
	},
	email: {
		label: "E-mail per la conferma",
		help: "Invieremo a questo indirizzo una copia della dichiarazione e la conferma della sua ricezione.",
		requiredError: "Inserisci un indirizzo e-mail per la conferma.",
		invalidError: "Controlla che l’indirizzo e-mail sia corretto.",
	},
	contractReference: {
		label: "Numero d’ordine o altri dati dell’acquisto",
		help: "Trovi il numero nella conferma dell’ordine. Se non lo hai a disposizione, descrivi l’acquisto, ad esempio indicando il prodotto e la data approssimativa dell’ordine.",
		requiredError: "Inserisci dati che ci permettano di identificare l’acquisto.",
	},
	scopeLabel: "A che cosa si riferisce il recesso?",
	scopeWhole: "All’intero ordine",
	scopePartial: "Solo ad alcuni prodotti",
	itemsLabel: "Prodotti e quantità",
	itemsHelp:
		"Indica il nome o il codice del prodotto e la quantità. Il nome non deve coincidere esattamente con il catalogo, purché il prodotto sia identificabile.",
	itemsRequiredError: "Indica i prodotti interessati e le rispettive quantità.",
	pickupInterest: "Vorrei un preventivo per il ritiro",
	pickupHelp:
		"È solo una richiesta di prezzo. Ordineremo un ritiro a pagamento soltanto dopo la tua esplicita accettazione del costo.",
	noteLabel: "Messaggio aggiuntivo (facoltativo)",
	privacyNotice:
		"Utilizziamo questi dati per ricevere e gestire il recesso e adempiere agli obblighi legali. I dettagli sono nell’informativa sulla privacy.",
	reviewButton: "Controlla i dati",
	reviewTitle: "Controlla la dichiarazione",
	declarationWhole: "Con la presente recedo integralmente dal contratto di vendita identificato di seguito.",
	declarationPartial:
		"Con la presente recedo dal contratto di vendita identificato di seguito, limitatamente ai prodotti e alle quantità indicati.",
	finalExplanation:
		"Il pulsante qui sotto invia una dichiarazione di recesso dal contratto. Non si tratta soltanto di una richiesta di assistenza.",
	editButton: "Modifica i dati",
	submitButton: "Conferma recesso",
	submitting: "Invio della dichiarazione in corso…",
	acceptedTitle: "Abbiamo ricevuto la dichiarazione di recesso",
	acceptedBody:
		"Inviamo all’indirizzo e-mail indicato la conferma con il contenuto della dichiarazione e la data e l’ora del suo invio. Ti comunicheremo come procedere.",
	receiptNumberLabel: "Numero della pratica",
	submissionTimeLabel: "Data e ora di invio",
	receivedTimeLabel: "Data e ora di ricezione",
	saveReceipt: "Salva la conferma",
	emailIssue:
		"La dichiarazione è stata registrata, ma non siamo ancora riusciti a inviare la conferma via e-mail. Stiamo riprovando. Puoi salvare la conferma qui; il recesso resta registrato come ricevuto.",
	failedTitle: "Non è stato possibile ricevere la dichiarazione",
	failedBody: "Riprova oppure invia la dichiarazione a info@maky.store. I dati inseriti restano nel modulo.",
	unknownTitle: "Non è stato possibile verificare l’esito dell’invio",
	unknownBody:
		"Non possiamo stabilire con certezza se la dichiarazione è stata ricevuta. Controlla la posta. Per un nuovo tentativo utilizzeremo lo stesso identificativo, per evitare una doppia registrazione. Puoi anche inviare la dichiarazione a info@maky.store.",
	rateLimit: "L’invio è temporaneamente limitato. Riprova più tardi oppure scrivi a info@maky.store.",
	unavailable:
		"L’invio online non è attualmente disponibile. Puoi trasmettere la dichiarazione a info@maky.store o per posta. Stiamo lavorando al ripristino della funzione.",
	noScript:
		"La funzione interattiva richiede JavaScript. Puoi anche inviare la dichiarazione a info@maky.store o utilizzare il modulo da stampare.",
};
