query ProductListByCategory(
	$slug: String!
	$channel: String!
	$lang: LanguageCodeEnum!
	$slugLang: LanguageCodeEnum
	$first: Int
	$after: String
	$last: Int
	$before: String
	$sortBy: ProductOrder
	$filter: ProductFilterInput
) {
	category(slug: $slug, slugLanguageCode: $slugLang) {
		id
		name
		slug
		description
		seoDescription
		seoTitle
		translation(languageCode: $lang) {
			name
			slug
			description
			seoDescription
			seoTitle
		}
		backgroundImage {
			url
			alt
		}
		products(
			first: $first
			after: $after
			last: $last
			before: $before
			channel: $channel
			sortBy: $sortBy
			filter: $filter
		) {
			edges {
				node {
					...ProductListItem
				}
				cursor
			}
			pageInfo {
				hasNextPage
				hasPreviousPage
				startCursor
				endCursor
			}
			totalCount
		}
	}
}
