query ProductListByCollection(
	$slug: String!
	$channel: String!
	$lang: LanguageCodeEnum!
	$slugLang: LanguageCodeEnum
	$first: Int
	$after: String
	$sortBy: ProductOrder
	$filter: ProductFilterInput
) {
	collection(slug: $slug, channel: $channel, slugLanguageCode: $slugLang) {
		id
		name
		slug
		description
		seoDescription
		seoTitle
		translation(languageCode: $lang) {
			name
			slug
			description
			seoDescription
			seoTitle
		}
		backgroundImage {
			url
			alt
		}
		products(first: $first, after: $after, sortBy: $sortBy, filter: $filter) {
			edges {
				node {
					...ProductListItem
				}
				cursor
			}
			pageInfo {
				hasNextPage
				hasPreviousPage
				startCursor
				endCursor
			}
			totalCount
		}
	}
}
